# Generated by Django 3.2 on 2022-05-29 18:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=32, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32, verbose_name='Amount')),
                ('status', models.CharField(choices=[('in_queue', 'In the queue'), ('process', 'Processing'), ('success', 'Succeed'), ('canceled', 'Cancelled')], default='in_queue', max_length=8, verbose_name='Status')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Time create')),
                ('finish_datetime', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.client')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ClientQueueLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=36, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_lock', to='core.client')),
            ],
            options={
                'verbose_name': 'Client Queue Lock',
                'verbose_name_plural': 'Client Queue Locks',
            },
        ),
    ]
