# Generated by Django 3.2 on 2022-05-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttransaction',
            name='error_message',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Error message'),
        ),
    ]
